// EXPORTED CONSTANTS //
export const LOAD_CONTENT = "LOAD_CONTENT";
export const DETECT_DIMENSIONS = "DETECT_DIMENSIONS";
export const CHANGE_FONT_SIZE = "CHANGE_FONT_SIZE";
export const CHANGE_THEME = "CHANGE_THEME";
export const SET_READER_TEXT = "SET_READER_TEXT";
export const PLAY_PAUSE_READER = "PLAY_PAUSE_READER";
export const RESTART_READER = "RESTART_READER";
export const SET_CURRENT_UNIT = "SET_CURRENT_UNIT";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SHOW_SCROLL = "SHOW_SCROLL";
export const SET_LANGUAGE = "SET_LANGUAGE";