// EXPORTED CONSTANTS //
export const LOAD_CONTENT = "LOAD_CONTENT";
export const DETECT_DIMENSIONS = "DETECT_DIMENSIONS";
export const CHANGE_FONT_SIZE = "CHANGE_FONT_SIZE";
export const CHANGE_THEME = "CHANGE_THEME";